import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000', 
    paddingHorizontal: 15,
    paddingTop: 40,
  },
  header: {
    backgroundColor: 'rgba(8, 156, 8, 0.08)',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(129, 199, 132, 0.3)',
  },
  headerText: {
    color: '#81c784',
    fontSize: 22,
    fontWeight: 'bold',
  },
  subText: {
    color: '#999',      
    fontSize: 12,
    marginBottom: 20,    
    textAlign: 'center',
    marginLeft: 50,
    marginRight: 50,
  },
  button: {
    width: 260,
    backgroundColor: 'rgba(8, 156, 1, 0.22)',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'center', 
    marginTop: 430,
    borderBottomRightRadius: 20, 
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 20, 
    borderColor: 'rgba(128, 199, 132, 0.4)',
    borderWidth: 1,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    marginTop: 450
  },
  modalContent: {
    backgroundColor: '#000', 
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderColor: 'rgba(129, 199, 132, 0.4)',
    borderWidth: 2,
    height: 450,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
    textAlign: 'center',
  },
  modalSubtitle: {
    color: '#ccc',
    fontSize: 14,
    marginBottom: 15,
    textAlign: 'center',
  },
  modalButton: {
    width: 260,
    backgroundColor: '#000',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'center', 
    borderBottomRightRadius: 20, 
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 20,
    marginBottom: 10,
    marginTop: 10,
    borderColor: 'rgba(128, 199, 132, 0.4)',
    borderWidth: 2,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
