import { StyleSheet } from 'react-native';

export function makeStyles(colors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
      padding: 20,
      justifyContent: 'center',
    },
    title: {
      fontSize: 30,
      color: colors.text,
      textAlign: 'left',
      marginBottom: 30,
      marginLeft: 20,
      marginTop: 20,
      fontWeight: 'bold',
    },
    text: {
      fontSize: 18,
      color: colors.text,
      textAlign: 'center',
      marginTop: 25,
      marginBottom: 45,
      alignSelf: 'center',
      width: 250,
    },
    inputEmail: {
      width: 350,
      alignSelf: 'center',
      backgroundColor: colors.inputBg,
      color: colors.inputText,
      borderRadius: 5,
      padding: 10,
      marginBottom: 25,
      fontSize: 16,
      borderColor: colors.border,
      borderWidth: colors.background === '#F7F9FC' ? 2 : 1,
    },
    inputSenha: {
      width: 350,
      alignSelf: 'center',
      backgroundColor: colors.inputBg,
      color: colors.inputText,
      borderRadius: 5,
      padding: 10,
      paddingRight: 45, // 👈 espaço para o ícone
      marginBottom: 25,
      fontSize: 16,
      borderColor: colors.border,
      borderWidth: colors.background === '#F7F9FC' ? 2 : 1,
    },
    button: {
      width: 260,
      backgroundColor: 'rgba(8, 156, 1, 0.2)',
      padding: 15,
      borderRadius: 12,
      alignItems: 'center',
      alignSelf: 'center',
      marginTop: 10,
      borderBottomRightRadius: 20,
      borderBottomLeftRadius: 0,
      borderTopRightRadius: 0,
      borderTopLeftRadius: 20,
      borderColor: colors.border,
      borderWidth: colors.background === '#F7F9FC' ? 2 : 1,
    },
    buttonText: {
      color: colors.text,
      fontSize: 18,
      fontWeight: 'bold',
    },
    image: {
      width: 300,
      height: 250,
      marginBottom: 40,
      marginTop: -30,
      alignSelf: 'center',
    },
    header: {
      flexDirection: 'row',
      marginBottom: 25,
      gap: 10,
    },
    errorText: {
      color: 'rgba(255, 138, 138, 0.5)',
      marginTop: -20,
      marginBottom: 5,
      marginLeft: 15,
      fontSize: 12,
    },
    forgotLink: {
      color: colors.text,
      fontSize: 14,
      textDecorationLine: 'underline',
      fontWeight: colors.background === '#F7F9FC' ? '700' : '500',
    },
    linkText: {
      color: colors.text,
      fontSize: 14,
      textDecorationLine: 'underline',
      fontWeight: colors.background === '#F7F9FC' ? '600' : '500',
    },
  });
}
