import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000', 
    paddingHorizontal: 15,
    paddingTop: 40,
  },
  header: {
    backgroundColor: 'rgba(8, 156, 8, 0.08)',
    padding: 15,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(129, 199, 132, 0.3)',
  },
  headerText: {
    color: '#81c784',
    fontSize: 22,
    fontWeight: 'bold',
  },
  subText: {
    color: '#999',      
    fontSize: 12,
    marginBottom: 20,    
    textAlign: 'center',
    marginLeft: 50,
    marginRight: 50,
  },
  button: {
    width: 260,
    backgroundColor: 'rgba(8, 156, 1, 0.22)',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'center', 
    marginTop: 30,
    borderBottomRightRadius: 20, 
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 20, 
    borderColor: 'rgba(128, 199, 132, 0.4)',
    borderWidth: 1,
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    marginTop: 450
  },
  modalContent: {
    backgroundColor: '#000', 
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderColor: 'rgba(129, 199, 132, 0.4)',
    borderWidth: 2,
    height: 450,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
    textAlign: 'center',
  },
  modalSubtitle: {
    color: '#ccc',
    fontSize: 14,
    marginBottom: 15,
    textAlign: 'center',
  },
  modalButton: {
    width: 260,
    backgroundColor: '#000',
    padding: 15,
    borderRadius: 12,
    alignItems: 'center',
    alignSelf: 'center', 
    borderBottomRightRadius: 20, 
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 0,
    borderTopLeftRadius: 20,
    marginBottom: 10,
    marginTop: 10,
    borderColor: 'rgba(128, 199, 132, 0.4)',
    borderWidth: 2,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },    
  input: {
    backgroundColor: '#2a2a2a',
    color: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
    fontSize: 16,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#57FF5A',
    borderRadius: 4,
    marginRight: 10,
  },
  checkboxMarcado: {
    backgroundColor: '#57FF5A',
  },
  checkboxTexto: {
    color: '#fff',
    fontSize: 14,
  },
  modalButtonCancelar: {
    backgroundColor: '#666',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  transacaoItem: {
    flexDirection: 'row',
    backgroundColor: '#1a1a1a',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  transacaoDescricao: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  transacaoCategoria: {
    color: '#999',
    fontSize: 14,
    marginTop: 4,
  },
  transacaoData: {
    color: '#666',
    fontSize: 12,
    marginTop: 4,
  },
  transacaoValor: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  valorPositivo: {
    color: '#57FF5A',
  },
  valorNegativo: {
    color: '#ff5757',
  },
  botaoDeletar: {
    backgroundColor: '#ff5757',
    padding: 6,
    borderRadius: 4,
    marginTop: 8,
  },
  textoDeletar: {
    color: '#fff',
    fontSize: 12,
  },
  secaoTitulo: {
    color: '#57FF5A',
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 10,
  },
  textoVazio: {
    color: '#666',
    textAlign: 'center',
    padding: 20,
  },
  botaoFlutuante: {
  position: 'absolute',
  bottom: 150, // distância da parte inferior da tela
  alignSelf: 'center', 
  width: 261,
  height: 40,
  backgroundColor: 'rgba(8, 156, 8, 0.6)',
  borderWidth: 1,
  borderColor: 'rgba(129, 199, 132, 0.4)',
  borderTopLeftRadius: 0,
  borderTopRightRadius: 20,
  borderBottomLeftRadius: 20,
  borderBottomRightRadius: 0,
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000', // sombra leve
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.3,
  shadowRadius: 3,
  elevation: 4, // sombra no Android
},
botaoFlutuanteTexto: {
  color: '#fff',
  fontWeight: 'bold',
  fontSize: 16,
},

});
